package com.heclient.heapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.heclient.heapp.db.PhoneNum;
import com.heclient.heapp.db.ResultInfo;
import com.heclient.heapp.db.User;

import com.heclient.heapp.db.PhoneNumDao;
import com.heclient.heapp.db.ResultInfoDao;
import com.heclient.heapp.db.UserDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig phoneNumDaoConfig;
    private final DaoConfig resultInfoDaoConfig;
    private final DaoConfig userDaoConfig;

    private final PhoneNumDao phoneNumDao;
    private final ResultInfoDao resultInfoDao;
    private final UserDao userDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        phoneNumDaoConfig = daoConfigMap.get(PhoneNumDao.class).clone();
        phoneNumDaoConfig.initIdentityScope(type);

        resultInfoDaoConfig = daoConfigMap.get(ResultInfoDao.class).clone();
        resultInfoDaoConfig.initIdentityScope(type);

        userDaoConfig = daoConfigMap.get(UserDao.class).clone();
        userDaoConfig.initIdentityScope(type);

        phoneNumDao = new PhoneNumDao(phoneNumDaoConfig, this);
        resultInfoDao = new ResultInfoDao(resultInfoDaoConfig, this);
        userDao = new UserDao(userDaoConfig, this);

        registerDao(PhoneNum.class, phoneNumDao);
        registerDao(ResultInfo.class, resultInfoDao);
        registerDao(User.class, userDao);
    }
    
    public void clear() {
        phoneNumDaoConfig.clearIdentityScope();
        resultInfoDaoConfig.clearIdentityScope();
        userDaoConfig.clearIdentityScope();
    }

    public PhoneNumDao getPhoneNumDao() {
        return phoneNumDao;
    }

    public ResultInfoDao getResultInfoDao() {
        return resultInfoDao;
    }

    public UserDao getUserDao() {
        return userDao;
    }

}
